language: java

sudo: false

jdk:
  - oraclejdk7
  - oraclejdk8

before_install:  
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS=-Xmx512m"
 - "echo $JAVA_OPTS"

script:
 - mvn clean install
 - cd contrib && mvn clean install

